### ISSUE TITLE
Enable multi-OS testing support (Travis CI)

### ISSUE THREAD

**Issue by ghost** [FreeRCT/FreeRCT#113]
_Note_: This is currently a beta [feature](http://docs.travis-ci.com/user/multi-os/) and requires emailing the Travis CI support team to have it enabled for a repository (I recently did this for another project).

**Comment by ghost** [comment]
If this seems worth pursuing (at some point), I can email the support team and ask if they will enable the feature for this repo.

**Comment by Alberth289346** [comment]
I have no objections.

The non-used constant was a surprise though, I would have expected that the compiler would catch that. As such, I should also check what compiler flags are used, maybe I am using obsolete settings?

**Comment by LordAro** [comment]
This would be a good idea indeed, but I suspect they'll say no unless we're
on their new container format -
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
- but currently their apt whitelist is missing some packages (sdl2 is
  known) due to them still running 12.04 on their testing platform...

**Comment by ghost** [comment]
For moving to the container format, https://github.com/travis-ci/apt-source-whitelist/issues/45 will hopefully be of some help if/when it is added. :)

**Comment by LordAro** [comment]
Indeed. Hopefully that gets the sdl-ttf libraries added too

**Comment by ghost** [comment]
sdl-ttf packages are now available: https://github.com/travis-ci/apt-package-whitelist/pull/673

**Comment by ghost** [comment]
Enabled in #144.
