### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by Noordfrees** [FreeRCT/FreeRCT#209]
I've written a simple website for FreeRCT using GitHub Pages. The result is at https://noordfrees.github.io/FreeRCT/. Play around a bit on the various subpages and try it at different browser window sizes :)

Of course there's still room for improvement. Also some parts of the stuff in `doc/` are now superfluous and should probably be moved to the website folder completely.

The code is in https://github.com/Noordfrees/FreeRCT/tree/gh-pages/docs.

- Do we want to move the site from my fork to the main repo and make it official?
- Feedback, opinions, suggestions appreciated :)

**Comment by Alberth289346** [comment]
Hai,

Some comments:
### Home page
I think at least some (or maybe all) of the "simpler" screenshots should not be there. It should give a positive impression what you can build, and some road and/or a single shop (and a few others) don't quite do that. Aim for few good shots rather than many bad ones imho. Likely the set should be expanded, make an issue for that marked "good first issue", and wait :)

### News
The time stamp is way too long. Just have the date, time is irrelevant imho (order implies increasing time sufficiently).

At the home page it says "news", at the page itself it's a "news archive". As the news is at the home page too, I think the latter is the better name. Then, it's quite non-relevant, so position it at the far right of the top-menubar.

### Download
Is not just download, but also dailies and compiling from source. My first idea is "Get it!", or "Install" as name?

As an idea, should there be a checksum file for checking integrity?

For building from source, step 3 should be before step 2, CMake options should be part of step 3, and likely, the `~` thing needs to be shown explicitly as well or it will be missed. I'd say fold it into the build procedure of step 2, with a # comment saying ~ will be expanded at runtime rather than compile time. I think that would be enough for knowledgeable readers to catch something special is happening there. (Experts typically don't read much, so burying it in 4 lines of text of an option is hidden too well I think.)

The `--help` thing should be near the "start freerct" line. Maybe the document generator put the option table wrong here?

A less large explanation might also work. Instead of a big table, add comments that state the options into the build script in a ready-to-use manner + `# few words explaining the option`. Point at the documentation for details, so it can be found easily. Eg something like
``` sh
# Construct build directory and enter it
$ mkdir build
$ cd build

# Generate Makefile, some build options are
#   -DCMAKE_INSTALL_PREFIX=/usr/local  # Set install directory, default is /usr
#   -DASAN=yes   # Link with ASAN memory checker
#   -DUSERDATAPREFIX="~/freerct_data" # FreeRCT expands the ~ to the user directory at runtime
#   -DVERSION_STRING  # set custom version string
# Further details can be found in the README(?) file in the root source directory.
$ cmake ..

# Compile and install
$ make
$ make install  # Can be skipped
```
Note that running the program is not only relevant when you build from source, so it should be separate imho

### Manual

I like it!

You could stick one or two images from it in the screenshot at the home page (a lot are from the same angle and the same game, you don't want to show the same thing several times (even though the windows at it are different, but people tend to not read those and thus don't count as "different", I think.

Assuming you have a savegame, you could rotate and take another shot for variation (at the home page).

The manual is a bit long, but on the other hand, it's a single page, which is useful. Eventually it should be split probably, You can either leave it as is now, or add a few links in the page to jump around.

### Screenshots

Is fine.

"test images" is a nice name. Eventually, you want to throw these out.

You didn't add any of your own which I think is worthwhile to do as well (the game also includes all your graphics too).

### Development

The page itself says "contribute" which is not the same as "development" (non-coders won't read "development" I think, they may be attracted to "contribute" or the more action-oriented "give a hand!", or perhaps "help improving!" or something)

There is one long "wall" of text, and the second line says "Development happens on our GH repo". At that point, you've lost pretty much everybody except the coders (and those don't even need this page at all, as they know the routine).

Make more specialized headings for different kinds of help. (translations, graphics, testing, ...). Basically you want to avoid a person to skip all the text he cannot do.

With these things, it helps if you imagine you are one of the target audience, eg a translator (but there are others). Check how much useless text he has to read before getting the text he does want to read. Keep in mind that words like C++ and SDL and other technical stuff outside their area of interest is a big turn-off to them, they have no clue what you're saying.
It reads something lilke "you must qdergry and also eegoftujk is useful, we can provide walrrujhu7tj and aeergrtj".

I hope you agree that after one line of that, the conclusion is "too difficult for me" and they stop reading. So this should be avoided imho. (That is, think from your audience.)


### Conclusion

In all, good work. I see no objections to make it official. And yes, we don't want duplicate information so move stuff as you see fit.

PS Did you see how I inserted "Conclusion" above to draw your attention? Would you have the same reading experience if I would have not added that header? This is what I mean in "development", give people hints what to read and what to skip.

**Comment by Alberth289346** [comment]
For development, you may want to order on the kind of help you want most, and put the non-coders above the coders. (The latter group hardly need any help in general, every single GH project can use help and they know it.)

**Comment by Alberth289346** [comment]
Oh, I have an issue that I forgot about:
![Screenshot from 2021-08-23 13-39-33](https://user-images.githubusercontent.com/3254232/130444550-5e7d8e65-05b8-482d-a3ef-c4f1d5174d74.png)

note the weird superscript box, it's attached to most links at that page.

**Comment by Noordfrees** [comment]
Thanks for the extensive feedback! I think I addressed all points now, the new version will be up in a few minutes

**Comment by Noordfrees** [comment]
Regarding checksums, in #207 every artifact is a Zip file containing the installer plus a file with the installer's checksum. I'll add this info to the website – but only after the branch is merged in case there will be more changes.

And one other thing, do we want to add the website files to the `master` branch or keep it as a separate `gh-pages` branch? 
Note that all website-related files are required to be placed in a folder called `docs/` (which is confusing as we also have a `doc/` folder). And if we have a server and domain of our own in the future we'll want to add more (server-side) scripting as well, and possibly split it off into a project of its own. 
On the other hand information might become outdated more quickly, and having just one branch would make it easier to update the website every time new features are added. 
What do you think is better?

**Comment by Alberth289346** [comment]
Nice about the checksum.

----
As for where to put the site, I lean towards keeping it in master, so it's simpler to keep it in sync, and also be able to pull old versions from the history if the need arises.

----
As for `doc`, it looks like we have a bit of user documentation in there (which I guess is what you wrote as becoming obsolete), and some development stuff. Perhaps to reduce confusion, Move the user stuff in your new documentation, and move the developer docs to different directory, eg `developer_docs` or something? (Bit long and very dedicated, other option is to have a `developer` directory to store it, technically you'd need a `docs` sub-directory then, but until we have actually have something else to store there, we can skip `docs` as subdir probabvly.)

Assuming that results in an empty `doc` directory, it can be deleted.
