### ISSUE TITLE
FreeRCT does not respect the XDG Base Directory Specification

### ISSUE THREAD

**Issue by Newbytee** [FreeRCT/FreeRCT#231]
Currently, it seems that FreeRCT just places saves in `~/OFF`. To be compliant with the XDG Base Directory Specification, it should instead store saves in whatever path `$XDG_DATA_HOME` points to, and if it is not set, default to `~/.local/share`.

See https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html for more information.

**Comment by Noordfrees** [comment]
https://github.com/FreeRCT/FreeRCT/blob/3a72892d1475e8e3eab3b0e69c6cc308ac8e621e/CMakeLists.txt#L19-L23

I guess the use of `option` here causes `USERDATA_PREFIX` to expand to OFF by default as CMake options can only be ON or OFF. When explicitly setting a `USERDATA_PREFIX` then it works correctly, on my system data is stored in `~/.config/freerct/` and `~/.local/share/freerct/`.

Should probably be something like
```cmake
IF(NOT DEFINED USERDATA_PREFIX)
	IF(WIN32)
		set(USERDATA_PREFIX "~/.freerct")
	ELSE()
		# Read XDG_DATA_HOME if available or use some default path
		...
	ENDIF()
ENDIF()
```

**Comment by Newbytee** [comment]
> When explicitly setting a USERDATA_PREFIX then it works correctly, on my system data is stored in ~/.config/freerct/ and ~/.local/share/freerct/.

Does it respect `$XDG_DATA_HOME`?

**Comment by fnetX** [comment]
When changing the defaults, make sure to add a migration of the data :)

**Comment by Newbytee** [comment]
> When changing the defaults, make sure to add a migration of the data :)

I wonder if this is necessary given that there hasn't been a formal release yet.

**Comment by fnetX** [comment]
If it isn't much effort, adding it might be a good idea. People who tried this, and will try again in the future, will wonder where their games are. Shouldn't it be as easy as checking if the previous location exists and moving the data (or asking to)?

**Comment by Noordfrees** [comment]
The problem that the dir defaults to `OFF` instead of a proper path has been fixed with one of the recent PRs, the default is now `"~/.freerct"` on Windows and `"~/.config/freerct"` on all other platforms.

Until now I've been storing the **installation data** (RCD files etc) in `~/.local/share/freerct/` and my **user data** (savegames, config file) in `~/.config/freerct/`. From the opening post it seems that normally, savegames should instead be stored in the first location, so where should the installation data of a non-system-wide install be stored then?

*(The CMake variables controlling these directories are `USERDATA_PREFIX` which defines where savegames are stored, and `CMAKE_INSTALL_PREFIX` as installation data is installed to `${CMAKE_INSTALL_PREFIX}/share/freerct`.)*

**Comment by Newbytee** [comment]
> Until now I've been storing the installation data (RCD files etc) in ~/.local/share/freerct/ and my user data (savegames, config file) in ~/.config/freerct/. From the opening post it seems that normally, savegames should instead be stored in the first location, so where should the installation data of a non-system-wide install be stored then?

I think RCD files should be located somewhere in the same directory as the binary executable, but XDG_DATA_HOME wouldn't be too unreasonable either (though unconventional). Savegames should go in XDG_DATA_HOME as I see it, yes. I hadn't actually looked at where it stores them when I made the original post, I just noticed that setting `~/OFF` as persistent in the Flatpak made savegames persist instead of getting deleted when the application was restarted (the proper way to do this would be actually respecting the XDG Base Directory Spec).

**Comment by Noordfrees** [comment]
You mean putting all RCD files and other assets in /usr/bin or .local/bin? That sounds weird to me… 

Would it be OK to use two subdirs `$XDG_DATA_HOME/freerct/data` and `$XDG_DATA_HOME/freerct/user` which store the installation and user data respectively? Then all data would be under XDG_DATA_HOME but it would still be cleanly separated.
For a user install, the default structure would then be
```sh
~/.local/bin/freerct                # Binary
~/.local/share/freerct/data/*.rcd   # Install data
~/.local/share/freerct/user/*.fct   # Savegames and config
```
and for a system-wide install or the .deb package
```sh
/usr/bin/freerct                    # Binary
/usr/share/freerct/data/*.rcd       # Install data
~/.local/share/freerct/user/*.fct   # Savegames and config
```

---

And another question. Currently the paths are hardcoded at compilation time, so the executable will then always look for files in e.g. `"~/.local/share/freerct"` if that was the path passed to CMake. If this path contains a '~' it is expanded to the user home directory at runtime. I assume that the XDG basedir spec requires us to instead check at *runtime* whether XDG_DATA_HOME is defined, and then decide whether to look for user data under this directory or a default directory, instead of hardcoding any path – correct?

**Comment by Newbytee** [comment]
> Would it be OK to use two subdirs $XDG_DATA_HOME/freerct/data and $XDG_DATA_HOME/freerct/user which store the installation and user data respectively? Then all data would be under XDG_DATA_HOME but it would still be cleanly separated.

Sounds okay to me, but what kind of user installation would use this? Some shell script installation? In a Flatpak installation, you install application data to e.g. /app/share (similar to /usr/share) inside the Flatpak sandbox and then data created at runtime (like savegames) are to be put into the XDG_DATA_HOME directory set by Flatpak, which also is inside the sandbox.

> And another question. Currently the paths are hardcoded at compilation time, so the executable will then always look for files in e.g. "~/.local/share/freerct" if that was the path passed to CMake. If this path contains a '~' it is expanded to the user home directory at runtime. I assume that the XDG basedir spec requires us to instead check at runtime whether XDG_DATA_HOME is defined, and then decide whether to look for user data under this directory or a default directory, instead of hardcoding any path – correct?

Yes, that's correct. It needs to be done at runtime so it can respect the values of environment variables.
