### ISSUE TITLE
Can't run FreeRCT like described in the readme

### ISSUE THREAD

**Issue by frankystone** [FreeRCT/FreeRCT#267]
I followed the instructions to download and compile FreeRCT, but trying to [run the game like described](https://github.com/FreeRCT/FreeRCT#running-the-program) doesn't work:

~~~~
$:> cd bin/
$:> ./freerct 
Failed creating directory '/home/kaputtnik/.local/share/freerct/save/' (File exists)
~~~~

The directory was created by the program, so i wonder why the message appears and exits. Next try:

~~~~
$:> ./freerct 
Data file data/font/Ubuntu-L.ttf is missing, the installation seems to be broken!
~~~~

Hm.... probably because i run from the `build/bin/` directory? The `data` folder is in the base directory (`FreeRCT/data/` after git clone) so i tried to run the binary from there:

~~~~
cd ../../
$:> build/bin/freerct 
Insufficient graphics loaded.
~~~~

Hm... maybe i have to use the `-u` switch:

~~~~
$:> cd build/bin/
$:> ./freerct -u /home/kaputtnik/Quellcode/FreeRCT/data/
Failed creating directory '/home/kaputtnik/Quellcode/FreeRCT/data//save/' (File exists)
~~~~

Ok, i know this message, next try:
~~~~
$:> ./freerct -u /home/kaputtnik/Quellcode/FreeRCT/
Data file data/font/Ubuntu-L.ttf is missing, the installation seems to be broken!
~~~~

And this also don't work for me:
~~~~
cd ../
$:> make run
Consolidate compiler generated dependencies of target rcdgen
[ 15%] Built target rcdgen
[ 23%] Built target rcd
Consolidate compiler generated dependencies of target freerct
[100%] Built target freerct
Data file data/font/Ubuntu-L.ttf is missing, the installation seems to be broken!
make[3]: *** [CMakeFiles/run.dir/build.make:70: CMakeFiles/run] Fehler 1
make[2]: *** [CMakeFiles/Makefile2:160: CMakeFiles/run.dir/all] Fehler 2
make[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/run.dir/rule] Fehler 2
make: *** [Makefile:189: run] Fehler 2
~~~~

What do i miss?

OS: archlinux

**Comment by Noordfrees** [comment]
Instead of `-u` try `-i`: `-u` sets the user data directory where savegames and the config file are stored, `-i` the installation directory where run-time assets and RCD files are stored. The easiest way to play the game is to use `make install` which ensures that FreeRCT will be able to find all assets. The default search paths when you don't want to Install the game are not taking the possibility of a separate build directory into account (yet, which will need to be fixed), so the relative paths of the two parts of the run-time assets are inconsistent.

Please try if running FreeRCT from the `build` directory  with `./bin/freerct -i bin` or from the `build/bin` directory with `./freerct -i ../..` works for you.

---

The "file exists" error looks really weird because we explicitly skip creating a directory if it exists: 
https://github.com/FreeRCT/FreeRCT/blob/236731fad864d631476f3d6d07638013c080314d/src/fileio.cpp#L264-L266
Which commit are you using? What is the output of `stat /home/kaputtnik/.local/share/freerct/save/`?

**Comment by frankystone** [comment]
> Please try if running FreeRCT from the `build` directory with `./bin/freerct -i bin` or from the `build/bin` directory with `./freerct -i ../..` works for you.

Both are working :-)

> The "file exists" error looks really weird because we explicitly skip creating a directory if it exists:

This error appears if the directory does __not__ exists yet. Just tried again by deleting `~/.local/share/freerct/` and starting the game. The result is the error message, but the directory is created. When starting again, all is fine (so the check works). I guess the culprit lies somewhere here:
https://github.com/FreeRCT/FreeRCT/blob/236731fad864d631476f3d6d07638013c080314d/src/fileio.cpp#L271-L277

**Comment by Noordfrees** [comment]
Good to hear :) I'll adjust the search paths to go up and down a few levels so that it should work from the top-level directory, `build`, and `build/bin` alike without adjusting the installdir, and update the README.

---

I guess the trailing '/' might be a problem. The function recurses to create all parent directories by simply cutting off everything from the last '/', but if the name ends with a '/' it seems to attempt to create in this order, starting at the first non-existent line: 
```
/
/home
/home/kaputtnik
/home/kaputtnik/.local
/home/kaputtnik/.local/share
/home/kaputtnik/.local/share/freerct
/home/kaputtnik/.local/share/freerct/save
/home/kaputtnik/.local/share/freerct/save/
```
The last two lines are two different ways of indicating the same directory, so the call to create the "parent directory" might also create the "child directory" in this case. Will prepare a fix.
