### ISSUE TITLE
Open/close button usability

### ISSUE THREAD

**Issue by Alberth289346** [FreeRCT/FreeRCT#293]
While trying the program, I had trouble with opening a ride. As an example the ice cream stall window:
![Screenshot from 2022-09-07 07-18-03](https://user-images.githubusercontent.com/3254232/188796761-bac75d55-fd55-443d-820e-a90e1ce2c116.png)

(ignore the tooltip bug, it's reported in #292  )

Apparently, the black dot says what light is "on", it's a bit counter-intuitive though, as an "on" light is normally more visible than an "off" light but the black dot makes the opposite happening. Perhaps a better alternative is to drop the black dot and make one light bright and the other light dim (or close to black)??

The second thing is that to switch the light you must very precisely click [EDIT: near the center] at the "off" light. I am not sure why I can't just click anywhere at/near either light, or even anywhere at the entire rectangle around it (although just the light is perhaps nicer).

**Comment by Noordfrees** [comment]
This is what if would look like to use a `GradientShift` instead of a black dot:
![image](https://user-images.githubusercontent.com/48293446/189104034-bdcbfbcf-7b1d-4e97-8221-ee0915f6b996.png) ![image](https://user-images.githubusercontent.com/48293446/189104059-15b013ac-17c4-45e0-9283-58ff1caa888e.png)
The disabled light is the darkest shift (`GS_NIGHT`), the enabled light is a medium highlighting factor (`GS_LIGHT`). Does this look better? Perhaps make the disabled light even darker?

For reference, RCT1:
![image](https://user-images.githubusercontent.com/48293446/189104616-d1d1e22a-081d-4938-8cfc-1cf18f0df7d6.png) ![image](https://user-images.githubusercontent.com/48293446/189104584-60cb451c-5f0b-4310-9316-25aa5392e25f.png)

**Comment by Alberth289346** [comment]
Your new version looks better (and sufficient) to me. Even if it's not clear immediately, once you see the other version I think it will be clear.

Rct1 is of course much better in having nice highlighting pixels at the right spots but it needs an artist to do such things well imho.
