### ISSUE TITLE
Crash when removing a path below a guest

### ISSUE THREAD

**Issue by GoogleCodeExporter** [FreeRCT/FreeRCT#38]
```
What steps will reproduce the problem?
1. build a path upwards
2. let the guest going there
3. remove path under the guest

What is the expected output?
guest fall down to tileground

What do you see instead?
programmcrash

NOT_REACHED triggered at line 167 of 
/home/niels/develop/git/freerct-read-only/src/person.cpp


```

Original issue reported on code.google.com by `vatriani.nn` on 11 Jan 2014 at 10:21
- Blocked on: #51

**Comment by ghost** [comment]
I'm making this comment mostly in order to remind myself to finish fixing this issue, since it shouldn't be that hard to finish. :P

Anyways, my current code, as I have stated before, allows guests to walk on ground tiles. The problem that arises is that 'steep' slopes occupy two voxels, which means that guests can hover above or be partially hidden behind these steep slopes.

I believe the best way to handle this will be to have the guests check which 'corner' they are in (N, E, S, W), based on `pix_pos.x` and `pix_pos.y`, and whether or not the corner is 'raised'. In doing so, we can then place the guest in the correct voxel (if they are not currently in the right one).

I'll continue updating this issue as time permits.
