### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [FreeRCT/FreeRCT#68]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [BackgroundWidget](https://github.com/FreeRCT/FreeRCT/blob/fbd5d744facc14c91c86f53f0e8f36d109177955/src/widget.cpp#L890)
- [GuiWindow](https://github.com/FreeRCT/FreeRCT/blob/fbd5d744facc14c91c86f53f0e8f36d109177955/src/window.cpp#L326)
- [ShowQuitProgram](https://github.com/FreeRCT/FreeRCT/blob/fbd5d744facc14c91c86f53f0e8f36d109177955/src/toolbar_gui.cpp#L451)

**Comment by elfring** [comment]
Are there a few more update candidates left over?

**Comment by LordAro** [comment]
Not that we could find

**Comment by elfring** [comment]
Is [the function "WindowManager::CloseAllWindows"](https://github.com/FreeRCT/FreeRCT/blob/13df96530a8c168395d9a5b3f5adf3684bfd2a78/src/window.cpp#L650) another update candidate?

**Comment by ghost** [comment]
No, or else it would have been included in the PR that fixed this issue. 

As stated in another issue by another member, please feel free to make pull requests with these changes you seem to think are worth making; otherwise, please do not waste the development team's time and sanity by opening a ton of issues reporting such small 'candidates'.

**Comment by elfring** [comment]
Should the attribute "top" be reset to an other pointer value by the member function "WindowManager::CloseAllWindows" so that an infinite loop will be avoided?
