### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [FreeRCT/FreeRCT#69]
Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html) ⇒ [RcdFileReader constructor](https://github.com/FreeRCT/FreeRCT/blob/fbd5d744facc14c91c86f53f0e8f36d109177955/src/fileio.cpp#L113)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html) ⇒ [WinMain](https://github.com/FreeRCT/FreeRCT/blob/fbd5d744facc14c91c86f53f0e8f36d109177955/src/windows/main_windows.cpp#L55)

**Comment by Alberth289346** [comment]
Instead of telling us in text what to do, why not make PRs?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html) a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/)?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in your software?

**Comment by Alberth289346** [comment]
I suggest that you spend your time on solving the problem by making a patch instead of explaining what you found. It's roughly equivalent in time to you, and less work to us, so it's a win overall.

I believe there are far bigger problems in the software than what any automagic aspect thingie can handle. Those should be done first imho.

**Comment by elfring** [comment]
The suggested tools can help to transform source code in various ways.
Which transformations are acceptable for you to be performed by another software tool automatically?

**Comment by ghost** [comment]
Locked due to appearance of 'automated' behavior by OP and disregard for genuine feedback provided by team members; this behavior was apparent in the other two issues opened by OP as well.

The team greatly welcomes and appreciates community involvement, but we would much prefer utilizing the issue tracker for actual game / engine bugs, features, etc. Please refer to our wiki/docs on how to contribute in the best way possible. Thanks for your time.
